### ISSUE TITLE
Publishing action seems to succeed when it should fail

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/github-actions-publish-to-github-packages#11]
I've seen two cases where the push to the Packages failed but the Action we're using succeeded:

1. @pierluigi [reported](https://github.slack.com/archives/CC3KANQ8Z/p1575457553234000) an issue where the Action should've reported a problem but still succeeded:
    > unauthorized: This operation would exceed the storage allotment for this account.
2. I had a package that [wasn't uniquely named](https://github.com/hectorsector/github-actions-for-packages/runs/333755098#step:4:243), so the action didn't succeed but it still reported successful:
    > blob upload invalid: Package "tic-tac-toe" is already associated with another repository.

In both of these cases, the course completed because of the reported success from the action, but should have actually failed.

**Comment by mattdavis0351** [comment]
@hectorsector This is quite old.  I think the current plan is to refactor courses to use the official Docker action to do this task.  I will not be updating the action I wrote anytime soon.

Not sure if this made the triage for swarming or not, but it'll be moot once we switch actions.

**Comment by hectorsector** [comment]
👋 @mattdavis0351 I was adding issues to the maintenance board in bulk -- we will have to go through a triaging process before we get going. 

For this one, does these issues still occur?  

> the Action should've reported a problem but still succeeded:
>> unauthorized: This operation would exceed the storage allotment for this account.

> I had a package that wasn't uniquely named, so the action didn't succeed but it still reported successful:
>> blob upload invalid: Package "tic-tac-toe" is already associated with another repository.

If they're still happening, I would consider these to be in-scope, low-priority issues. I consider the task here either look and see if we can do anything on the course end to help with this bug, if not open an issue in the action repo and consider these closed.

**Comment by mattdavis0351** [comment]
This no longer matters as we have switched to the official Docker action.  All error and exception handling is now on them!
